CREATE TABLE T_PACIENTES (
  ID_PACIENTES NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(20) NOT NULL,
  APELLIDO_P VARCHAR2(20) NOT NULL,
  APELLIDO_M VARCHAR2(20) NOT NULL,
  TIPO_DE_SANGRE VARCHAR2(3) NOT NULL,
  GENERO VARCHAR2(1) NOT NULL,
  FECHA_DE_ALTA DATE DEFAULT SYSDATE,
  CONSTRAINT CHK_TIPO_DE_SANGRE CHECK (TIPO_DE_SANGRE IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
  CONSTRAINT CHK_GENERO CHECK (GENERO IN ('M', 'F'))
);

CREATE TABLE T_MEDICOS(
    ID_MEDICO NUMBER PRIMARY KEY NOT NULL,
    NOMBRE_MEDICO VARCHAR(50) NOT NULL,
    APELLIDO_P VARCHAR(50) NOT NULL,
    APELLIDO_M VARCHAR(50),
    ESPECIALIDAD VARCHAR(50) NOT NULL,
    FECHA_CONTRATO DATE DEFAULT SYSDATE
);

CREATE TABLE T_EXPEDIENTES (
  ID_EXPEDIENTE NUMBER PRIMARY KEY,
  ID_MEDICO NUMBER NOT NULL,
  ID_PACIENTES NUMBER NOT NULL,
  FECHA_EXPEDIENTE DATE DEFAULT SYSDATE,
  DIAGNOSTICO VARCHAR2(200) NOT NULL,
  TRATAMIENTO VARCHAR2(200) NOT NULL,
  CONSTRAINT FK_MEDICOS FOREIGN KEY (ID_MEDICO) REFERENCES T_MEDICOS(ID_MEDICO),
  CONSTRAINT FK_PACIENTE FOREIGN KEY (ID_PACIENTES) REFERENCES T_PACIENTES(ID_PACIENTES)
);

ALTER TABLE T_PACIENTES
MODIFY APELLIDO_P  VARCHAR2(30);

ALTER TABLE T_PACIENTES
ADD CATEGORIA NUMBER(1)
CHECK (CATEGORIA IN (1, 2));

ALTER TABLE T_PACIENTES
RENAME COLUMN CATEGORIA TO TIPO_PACIENTE;

ALTER TABLE T_PACIENTES
DROP COLUMN TIPO_PACIENTE;

INSERT INTO T_PACIENTES (ID_PACIENTES, NOMBRE, APELLIDO_P, APELLIDO_M, TIPO_DE_SANGRE, GENERO)
VALUES (1, 'Juan', 'Perez', 'Lopez', 'O+', 'M');